name: Update Jira Task's fix version
description: "A GitHub Action to update fix version for Jira tasks based on diff"
branding:
  icon: "git-pull-request"
  color: purple
inputs:
  jiraAccount:
    description: "Jira account"
    required: true
  jiraToken:
    description: "Jira access token"
    required: true
  jiraHost:
    description: "Jira Host"
    required: false
    default: "taxify.atlassian.net"
  ticketRegexp:
    description: "Regexp of the Jira Ticket Number"
    required: true
  targetBranch:
    description: "Branch name to compare with [default: Master]"
    required: true
    default: "master"
runs:
  using: "node12"
  main: "dist/index.js"
