name: Update Jira Task's fix version
description: "A GitHub Action to update fix version for Jira tasks based on diff"
branding:
  icon: "git-pull-request"
  color: purple
inputs:
  github-token:
    description: "Token for GitHub access"
    required: true
  projectName:
    description: "Xcode pbxprodj file name"
    required: true
  versionPrefix:
    description: "It will be appended before version"
    required: true
  jiraAccount:
    description: "Jira account"
    required: true
  jiraToken:
    description: "Jira access token"
    required: true
  jiraHost:
    description: "Jira Host"
    required: true
    default: "taxify.atlassian.net"
  jiraProjectIds:
    description: "Ids of Jira Projects where to create release version \"1111, 11213\""
    required: true
  ticketRegexp:
    description: "Regexp of the Jira Ticket Number"
    required: true
  targetBranch:
    description: "Branch name to compare with [default: Master]"
    required: true
    default: "master"
  sourceBranch:
    description: "Branch name to compare from [default: Master]"
    required: true
runs:
  using: "node12"
  main: "dist/index.js"
